[ids]

*

# [global]
#
# unicode_method = xdotool    # for X11
# # unicode_method = wtype    # for Wayland

[main]

# Maps capslock to escape when pressed and control when held.
# capslock = overload(control, esc)

# Remaps the escape key to capslock
# esc = capslock

# leftalt = leftmeta
# leftmeta = leftalt

## For laptop use
# leftalt = overload(control, esc)
# leftcontrol = leftalt

rightalt = layer(umlauts)

## CONFLICTS WITH KITTY, works in GUI
[umlauts]

a = macro(C-S-u 0 0 e 4 enter)
o = macro(C-S-u 0 0 f 6 enter)
u = macro(C-S-u 0 0 f c enter)
s = macro(C-S-u 0 0 d f enter)

[umlauts+shift]

a = macro(C-S-u 0 0 c 4 enter)
o = macro(C-S-u 0 0 d 6 enter)
u = macro(C-S-u 0 0 d c enter)
