#!/usr/bin/env bash

## NOTE: Only counts $HOME/.config directory

. "$(dirname "$0")"/.nnn-plugin-helper

function preFlightCheck()
{
    TOOLS=(fuzscope filer)

    exitFlag=0;

    for TOOL in ${TOOLS[@]}; do 
        if [ -x "$(command -v $TOOL )" ]; then
            echo -ne "> Found $TOOL!      \r"
        else 
            echo "ERR: $TOOL doesn't exist."
            exitFlag=1;
        fi
    done

    if ((exitFlag == 1)); then
        echo "Please install prerequisites!"
        exit
    fi
}



if [ "$(cmd_exists fd)" -eq "0" ]; then
    sel=$(fd . --base-directory=$HOME/.config/ -L | fuzscope --base-directory $HOME/.config)
else
    sel=$(find ~/.config/ . | fuzscope)
fi

if [ -n "$sel" ]; then
    [ -d "$sel" ] && nnn_cd "$sel" "0" || (echo "$sel" | peek)
fi
