#!/bin/bash

if playerctl status &>/dev/null
then
    STATUS=$(playerctl status)
    ARTIST=$(playerctl metadata artist)
    ARTIST=${ARTIST:0:20}
    TITLE=$(playerctl metadata title)
    TITLE=${TITLE%%\?*}                                             ### for URLs, strip after the first '?'
    TITLE=${TITLE:0:25}...
    if [ "$STATUS" == "Playing" ]; then
        STATUSICON=""
    elif [ "$STATUS" == "Paused" ]; then
        STATUSICON=""
    fi
    [ -z "$ARTIST" ] && echo "$STATUSICON $TITLE" || echo "$STATUSICON $ARTIST - $TITLE"
    # echo "$STATUSICON $ARTIST - $TITLE"
    echo $TITLE
    exit 0
fi
if mpc status &>/dev/null
then
    STATUS=`mpc status`
    if [[ "$STATUS" == *"[playing]"* ]]
    then
        echo " $(mpc current)"
        echo `mpc current -f "%title%"`
        exit 0
    elif [[ "$STATUS" == *"[paused]"* ]]
    then
        echo " $(mpc current)"
        echo `mpc current -f "%title%"`
        exit 0
    fi
fi
