vim.g.mapleader = ','
vim.g.maplocalleader = '\\'

require 'cfg.settings'
require 'cfg.commands'
require 'cfg.mappings'
require 'cfg.lsp'
require 'cfg.plugins'
require 'cfg.autocmds'
require 'cfg.folding'
require 'cfg.abbreviations'
